// <auto-generated />
using System;
using GenesisMarket.Domain.Enums;
using GenesisMarket.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace GenesisMarket.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810162116_AddUserIsDeleted")]
    partial class AddUserIsDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "category", new[] { "realestate", "transport", "electronics", "home", "fashion", "kids", "work", "services", "animals", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "city", new[] { "tiraspol", "bendery", "rybnitsa", "dubossary", "slobodzea", "grigoriopol", "dnestrovsk" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "condition", new[] { "new", "used", "notapplicable" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "listing_status", new[] { "draft", "pendingreview", "active", "sold", "archived", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "price_type", new[] { "fixed", "negotiable", "free" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.HasIndex("ListingId", "BuyerId")
                        .IsUnique();

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Category>("Category")
                        .HasColumnType("category");

                    b.Property<City>("City")
                        .HasColumnType("city");

                    b.Property<Condition>("Condition")
                        .HasColumnType("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(12,0)");

                    b.Property<PriceType>("PriceType")
                        .HasColumnType("price_type");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector");

                    b.Property<ListingStatus>("Status")
                        .HasColumnType("listing_status");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("OwnerId", "Status");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("Category", "City", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("listings", null, t =>
                        {
                            t.HasCheckConstraint("ck_listings_description_length", "char_length(\"Description\") <= 5000");

                            t.HasCheckConstraint("ck_listings_district_length", "\"District\" IS NULL OR char_length(\"District\") <= 100");

                            t.HasCheckConstraint("ck_listings_price_nonnegative", "\"Price\" IS NULL OR \"Price\" >= 0");

                            t.HasCheckConstraint("ck_listings_price_pricetype", "(\"PriceType\" = 'free' AND \"Price\" = 0) OR (\"PriceType\" = 'negotiable' AND \"Price\" IS NULL) OR (\"PriceType\" = 'fixed' AND \"Price\" IS NOT NULL AND \"Price\" >= 0)");

                            t.HasCheckConstraint("ck_listings_title_length", "char_length(\"Title\") >= 5 AND char_length(\"Title\") <= 120");

                            t.HasCheckConstraint("ck_listings_views_nonnegative", "\"ViewsCount\" >= 0");
                        });
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "SortOrder");

                    b.ToTable("listing_images", (string)null);
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_messages_text_length", "char_length(\"Text\") <= 2000");
                        });
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<City>("City")
                        .HasColumnType("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("ShowPhoneInListing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ViberEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("WhatsappEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("UserId");

                    b.ToTable("profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_profiles_display_name_length", "char_length(\"DisplayName\") <= 60");
                        });
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Category>("Category")
                        .HasColumnType("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Slug")
                        .IsUnique();

                    b.ToTable("subcategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = Category.RealEstate,
                            Name = "Квартиры",
                            Slug = "kvartiry"
                        },
                        new
                        {
                            Id = 2,
                            Category = Category.RealEstate,
                            Name = "Дома, дачи, коттеджи",
                            Slug = "doma"
                        },
                        new
                        {
                            Id = 3,
                            Category = Category.RealEstate,
                            Name = "Комнаты",
                            Slug = "komnaty"
                        },
                        new
                        {
                            Id = 4,
                            Category = Category.RealEstate,
                            Name = "Земельные участки",
                            Slug = "zemelnye-uchastki"
                        },
                        new
                        {
                            Id = 5,
                            Category = Category.RealEstate,
                            Name = "Гаражи и машиноместа",
                            Slug = "garazhi"
                        },
                        new
                        {
                            Id = 6,
                            Category = Category.RealEstate,
                            Name = "Коммерческая недвижимость",
                            Slug = "kommercheskaya"
                        },
                        new
                        {
                            Id = 7,
                            Category = Category.Transport,
                            Name = "Легковые автомобили",
                            Slug = "legkovye-avto"
                        },
                        new
                        {
                            Id = 8,
                            Category = Category.Transport,
                            Name = "Грузовики и спецтехника",
                            Slug = "gruzoviki"
                        },
                        new
                        {
                            Id = 9,
                            Category = Category.Transport,
                            Name = "Мотоциклы и мототехника",
                            Slug = "mototsikly"
                        },
                        new
                        {
                            Id = 10,
                            Category = Category.Transport,
                            Name = "Запчасти и аксессуары",
                            Slug = "zapchasti"
                        },
                        new
                        {
                            Id = 11,
                            Category = Category.Transport,
                            Name = "Водный транспорт",
                            Slug = "vodnyy-transport"
                        },
                        new
                        {
                            Id = 12,
                            Category = Category.Electronics,
                            Name = "Телефоны",
                            Slug = "telefony"
                        },
                        new
                        {
                            Id = 13,
                            Category = Category.Electronics,
                            Name = "Ноутбуки",
                            Slug = "noutbuki"
                        },
                        new
                        {
                            Id = 14,
                            Category = Category.Electronics,
                            Name = "Компьютеры и комплектующие",
                            Slug = "kompyutery"
                        },
                        new
                        {
                            Id = 15,
                            Category = Category.Electronics,
                            Name = "Телевизоры и проекторы",
                            Slug = "tv"
                        },
                        new
                        {
                            Id = 16,
                            Category = Category.Electronics,
                            Name = "Фото и видео",
                            Slug = "foto-video"
                        },
                        new
                        {
                            Id = 17,
                            Category = Category.Electronics,
                            Name = "Аудиотехника",
                            Slug = "audio"
                        },
                        new
                        {
                            Id = 18,
                            Category = Category.Home,
                            Name = "Мебель",
                            Slug = "mebel"
                        },
                        new
                        {
                            Id = 19,
                            Category = Category.Home,
                            Name = "Бытовая техника",
                            Slug = "bytovaya-tehnika"
                        },
                        new
                        {
                            Id = 20,
                            Category = Category.Home,
                            Name = "Ремонт и стройка",
                            Slug = "remont-stroyka"
                        },
                        new
                        {
                            Id = 21,
                            Category = Category.Home,
                            Name = "Сад и огород",
                            Slug = "sad-ogorod"
                        },
                        new
                        {
                            Id = 22,
                            Category = Category.Home,
                            Name = "Посуда и товары для дома",
                            Slug = "posuda"
                        },
                        new
                        {
                            Id = 23,
                            Category = Category.Fashion,
                            Name = "Мужская одежда",
                            Slug = "muzhskaya-odezhda"
                        },
                        new
                        {
                            Id = 24,
                            Category = Category.Fashion,
                            Name = "Женская одежда",
                            Slug = "zhenskaya-odezhda"
                        },
                        new
                        {
                            Id = 25,
                            Category = Category.Fashion,
                            Name = "Обувь",
                            Slug = "obuv"
                        },
                        new
                        {
                            Id = 26,
                            Category = Category.Fashion,
                            Name = "Аксессуары",
                            Slug = "aksessuary"
                        },
                        new
                        {
                            Id = 27,
                            Category = Category.Kids,
                            Name = "Детская одежда и обувь",
                            Slug = "detskaya-odezhda"
                        },
                        new
                        {
                            Id = 28,
                            Category = Category.Kids,
                            Name = "Игрушки",
                            Slug = "igrushki"
                        },
                        new
                        {
                            Id = 29,
                            Category = Category.Kids,
                            Name = "Коляски",
                            Slug = "kolyaski"
                        },
                        new
                        {
                            Id = 30,
                            Category = Category.Kids,
                            Name = "Детская мебель",
                            Slug = "detskaya-mebel"
                        },
                        new
                        {
                            Id = 31,
                            Category = Category.Work,
                            Name = "Вакансии",
                            Slug = "vakansii"
                        },
                        new
                        {
                            Id = 32,
                            Category = Category.Work,
                            Name = "Резюме",
                            Slug = "rezume"
                        },
                        new
                        {
                            Id = 33,
                            Category = Category.Services,
                            Name = "Строительство и ремонт",
                            Slug = "stroitelstvo-remont"
                        },
                        new
                        {
                            Id = 34,
                            Category = Category.Services,
                            Name = "Красота и здоровье",
                            Slug = "krasota-zdorovie"
                        },
                        new
                        {
                            Id = 35,
                            Category = Category.Services,
                            Name = "Обучение и курсы",
                            Slug = "obuchenie"
                        },
                        new
                        {
                            Id = 36,
                            Category = Category.Services,
                            Name = "Перевозки и грузчики",
                            Slug = "perevozki"
                        },
                        new
                        {
                            Id = 37,
                            Category = Category.Services,
                            Name = "Ремонт техники",
                            Slug = "remont-tehniki"
                        },
                        new
                        {
                            Id = 38,
                            Category = Category.Animals,
                            Name = "Собаки",
                            Slug = "sobaki"
                        },
                        new
                        {
                            Id = 39,
                            Category = Category.Animals,
                            Name = "Кошки",
                            Slug = "koshki"
                        },
                        new
                        {
                            Id = 40,
                            Category = Category.Animals,
                            Name = "Птицы",
                            Slug = "ptitsy"
                        },
                        new
                        {
                            Id = 41,
                            Category = Category.Animals,
                            Name = "Товары для животных",
                            Slug = "tovary-dlya-zhivotnyh"
                        },
                        new
                        {
                            Id = 42,
                            Category = Category.Other,
                            Name = "Разное",
                            Slug = "raznoe"
                        });
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BannedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneE164")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Channel", "CreatedAt");

                    b.ToTable("verification_codes", (string)null);
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("GenesisMarket.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenesisMarket.Domain.Entities.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenesisMarket.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("GenesisMarket.Domain.Entities.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesisMarket.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Listing", b =>
                {
                    b.HasOne("GenesisMarket.Domain.Entities.User", "Owner")
                        .WithMany("Listings")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenesisMarket.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany("Listings")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.ListingImage", b =>
                {
                    b.HasOne("GenesisMarket.Domain.Entities.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Message", b =>
                {
                    b.HasOne("GenesisMarket.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesisMarket.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Profile", b =>
                {
                    b.HasOne("GenesisMarket.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("GenesisMarket.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GenesisMarket.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.VerificationCode", b =>
                {
                    b.HasOne("GenesisMarket.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Listing", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.Subcategory", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("GenesisMarket.Domain.Entities.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Listings");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
